{% set name = "BacAnt" %}
{% set version = "3.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: /public3/Users/hongwj/project/Tmp/BacAnt/dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  entry_points:
    - bacant = BacAnt.bacant:run

requirements:
  host:
    - pip
    - python
    - bcbio-gff ==0.6.6
    - biopython ==1.76
    - colorlog ==4.2.1
    - matplotlib ==3.1.3
    - numpy ==1.19.0
    - pandas ==0.25.1
    - reportlab ==3.5.32
  run:
    - bcbio-gff ==0.6.6
    - biopython ==1.76
    - colorlog ==4.2.1
    - matplotlib ==3.1.3
    - numpy ==1.19.0
    - pandas ==0.25.1
    - python
    - reportlab ==3.5.32

test:
  imports:
    - BacAnt
    - BacAnt.Integron_Finder
    - BacAnt.Integron_Finder.integron_finder
    - BacAnt.Integron_Finder.scripts
  commands:
    - bacant --help

about:
  home: "https://github.com/xthua/bacant.git"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: 
  summary: "This program is designed for annotation of antimicrobal resistance(AMR), transposon(Tn) and integron(In) in bacteria"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
